language: node_js # 编译语言、环境

sudo: required # 需要管理员权限

dist: xenial # 指定 CI 系统版本为 Ubuntu16.04 LTS

node_js: stable #Node.js 版本

branches:
  only:
    - hexo # 只有 hexo 分支检出更改才触发 CI

before_install: 
  - export TZ='Asia/Shanghai' #配置时区为东八区 UTC+8
  - npm install hexo-cli # 安装 hexo
#  - sudo apt-get install libpng16-dev # 安装 libpng16-dev CI 编译出现相关报错时请取消注释

install:
  - npm install # 安装依赖
  - npm uni hexo-renderer-marked --save
  - npm i @upupming/hexo-renderer-markdown-it-plus --save

script: # 执行脚本，清除缓存，生成静态文件
  - hexo clean
  - hexo generate 

env:
  global:
    - GH_REF: git@github.com:AIkikaze/Jasmine_blog.git

after_script:
  - cd ./public
  - git init
  - git config user.name "${GIT_NAME}"
  - git config user.email "${GIT_EMAIL}"
  - git add .
  - git commit -m "TravisCI 自动部署"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
